#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ed2kIA — Public Launch Automation Script (Sprint19)
# ─────────────────────────────────────────────────────────────────────────────
# Idempotent public launch automation with automatic rollback.
# Feature gate: v2.1-public-launch
#
# Usage:
#   ./scripts/launch-day.sh [--dry-run] [--profile PROFILE] [--replicas N]
#
# Phases:
#   1. Validate environment (Docker, Rust, Python, WASM target, redb)
#   2. Execute pre-launch checks (audit-scan.sh, pre-launch-check.sh)
#   3. Launch docker-compose with production profile
#   4. Activate rate-limiting, SCTGuard, BFTAggregator in public mode
#   5. Verify healthchecks (/api/health, /api/metrics, /api/atlas/stats)
#   6. Generate launch-day-report-YYYYMMDD.md
#
# Exit:  🟢 LAUNCH SUCCESS  or  🔴 ROLBACK TRIGGERED: [causa]
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Options ────────────────────────────────────────────────────────────────

DRY_RUN=false
PROFILE="mainnet"
REPLICAS=1
REPORT_DATE=$(date +%Y%m%d)
REPORT_FILE="docs/launch-day-report-${REPORT_DATE}.md"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FINDINGS=()
PHASE=0

# ─── Colors ─────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# ─── Usage ──────────────────────────────────────────────────────────────────

usage() {
    cat <<'EOF'
ed2kIA Public Launch Automation — Sprint19

Usage: ./scripts/launch-day.sh [OPTIONS]

Options:
  --dry-run          Simulate launch without executing destructive actions
  --profile PROFILE  Docker compose profile (default: mainnet)
  --replicas N       Number of node replicas to launch (default: 1)
  -h, --help         Show this help message

Phases:
  1. Environment validation
  2. Pre-launch checks (audit + pre-launch)
  3. Docker compose launch
  4. Public mode activation (rate-limit, SCTGuard, BFT)
  5. Healthcheck verification
  6. Launch report generation

Exit Codes:
  0  🟢 LAUNCH SUCCESS
  1  🔴 ROLBACK TRIGGERED
EOF
}

# ─── Logging ────────────────────────────────────────────────────────────────

log_phase() {
    echo ""
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${MAGENTA}  PHASE $1: $2${NC}"
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    PHASE=$1
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_ok() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

log_dry() {
    echo -e "${CYAN}[DRY-RUN]${NC} $1"
}

# ─── Rollback ───────────────────────────────────────────────────────────────

rollback() {
    local cause="$1"
    echo ""
    echo -e "${RED}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${RED}  🔴 ROLBACK TRIGGERED: ${cause}${NC}"
    echo -e "${RED}═══════════════════════════════════════════════════════════════${NC}"
    echo ""

    if [[ "$DRY_RUN" == "false" ]]; then
        log_info "Stopping docker compose services..."
        cd "$PROJECT_ROOT"
        docker compose --profile "$PROFILE" -f deploy/docker-compose.yml down 2>/dev/null || true
        log_info "Rollback complete."
    else
        log_dry "Rollback would stop docker compose services."
    fi

    # Generate abort report
    cat > "$PROJECT_ROOT/$REPORT_FILE" <<EOF
# Launch Day Report — ABORTED ($REPORT_DATE)

## Status: 🔴 ROLBACK TRIGGERED

### Cause
$cause

### Phase Reached
Phase $PHASE

### Findings
$(for finding in "${FINDINGS[@]}"; do echo "- $finding"; done)

### Rollback Actions
- Docker compose services stopped
- Public mode deactivated

### Next Steps
1. Review findings above
2. Fix root causes
3. Re-run: \`./scripts/launch-day.sh\`

---
*Generated by scripts/launch-day.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

    log_info "Abort report written to: $REPORT_FILE"
    exit 1
}

cleanup() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        rollback "Non-zero exit code ($exit_code) at phase $PHASE"
    fi
}

trap cleanup EXIT INT TERM

# ─── Parse Arguments ────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --profile)
            PROFILE="$2"
            shift 2
            ;;
        --replicas)
            REPLICAS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# ─── Banner ─────────────────────────────────────────────────────────────────

echo ""
echo -e "${MAGENTA}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${MAGENTA}║           ed2kIA Public Launch Automation                     ║${NC}"
echo -e "${MAGENTA}║           Sprint19 — v2.1.0-sprint19                          ║${NC}"
echo -e "${MAGENTA}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${CYAN}⚡ DRY-RUN MODE — No destructive actions will be executed${NC}"
    echo ""
fi

# ─── Phase 1: Environment Validation ────────────────────────────────────────

log_phase 1 "Environment Validation"

check_command() {
    local cmd="$1"
    local desc="$2"
    if command -v "$cmd" &>/dev/null; then
        local version
        version=$("$cmd" --version 2>&1 | head -n1)
        log_ok "$desc: $version"
        return 0
    else
        FINDINGS+=("$desc not found ($cmd)")
        log_error "$desc not found ($cmd)"
        return 1
    fi
}

ENV_OK=true

check_command "docker" "Docker" || ENV_OK=false
check_command "cargo" "Rust/Cargo" || ENV_OK=false
check_command "python3" "Python3" || ENV_OK=false

# Check Docker Compose
if docker compose version &>/dev/null; then
    log_ok "Docker Compose: $(docker compose version --short 2>/dev/null || echo 'available')"
else
    FINDINGS+=("Docker Compose plugin not available")
    log_error "Docker Compose plugin not available"
    ENV_OK=false
fi

# Check WASM target
if rustup target list | grep -q "wasm32-wasi installed" 2>/dev/null; then
    log_ok "WASM target (wasm32-wasi): installed"
else
    log_warn "WASM target (wasm32-wasi) not installed — edge nodes will be limited"
fi

# Check redb dependency
if grep -q "redb" "$PROJECT_ROOT/Cargo.toml" 2>/dev/null; then
    log_ok "redb dependency: present in Cargo.toml"
else
    FINDINGS+=("redb dependency missing from Cargo.toml")
    log_error "redb dependency missing"
    ENV_OK=false
fi

# Check docker-compose.yml exists
if [[ -f "$PROJECT_ROOT/deploy/docker-compose.yml" ]]; then
    log_ok "docker-compose.yml: found"
else
    FINDINGS+=("deploy/docker-compose.yml not found")
    log_error "docker-compose.yml not found"
    ENV_OK=false
fi

if [[ "$ENV_OK" == "false" ]]; then
    rollback "Environment validation failed: ${#FINDINGS[@]} issue(s) found"
fi

# ─── Phase 2: Pre-Launch Checks ─────────────────────────────────────────────

log_phase 2 "Pre-Launch Checks"

# 2a. Audit scan
if [[ -f "$SCRIPT_DIR/audit-scan.sh" ]]; then
    log_info "Running audit-scan.sh..."
    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would execute: bash $SCRIPT_DIR/audit-scan.sh --dry-run"
    else
        if bash "$SCRIPT_DIR/audit-scan.sh" --dry-run 2>&1; then
            log_ok "Audit scan: PASSED"
        else
            FINDINGS+=("Audit scan failed")
            log_error "Audit scan failed"
        fi
    fi
else
    log_warn "audit-scan.sh not found — skipping"
fi

# 2b. Pre-launch checklist
if [[ -f "$SCRIPT_DIR/pre-launch-check.sh" ]]; then
    log_info "Running pre-launch-check.sh..."
    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would execute: bash $SCRIPT_DIR/pre-launch-check.sh"
    else
        if bash "$SCRIPT_DIR/pre-launch-check.sh" 2>&1; then
            log_ok "Pre-launch check: PASSED"
        else
            FINDINGS+=("Pre-launch check failed")
            log_error "Pre-launch check failed"
        fi
    fi
else
    log_warn "pre-launch-check.sh not found — skipping"
fi

# 2c. Cargo check
log_info "Running cargo check --lib..."
if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "Would execute: cargo check --lib"
else
    if cd "$PROJECT_ROOT" && cargo check --lib 2>&1 | tail -n5; then
        log_ok "Cargo check: PASSED"
    else
        FINDINGS+=("cargo check failed")
        rollback "cargo check failed — codebase not compile-ready"
    fi
fi

# ─── Phase 3: Docker Compose Launch ─────────────────────────────────────────

log_phase 3 "Docker Compose Launch (profile=$PROFILE, replicas=$REPLICAS)"

if [[ "$DRY_RUN" == "true" ]]; then
    log_dry "Would execute: docker compose --profile $PROFILE -f deploy/docker-compose.yml up -d --scale node=$REPLICAS"
    log_dry "Services will be started in background"
else
    log_info "Starting docker compose services..."
    cd "$PROJECT_ROOT"

    if docker compose --profile "$PROFILE" -f deploy/docker-compose.yml up -d 2>&1; then
        log_ok "Docker compose services started"
    else
        FINDINGS+=("Docker compose launch failed")
        rollback "Docker compose failed to start services"
    fi

    log_info "Waiting for services to initialize (10s)..."
    sleep 10
fi

# ─── Phase 4: Public Mode Activation ────────────────────────────────────────

log_phase 4 "Public Mode Activation"

activate_public_mode() {
    local endpoint="${1:-http://localhost:3000}"

    # 4a. Rate limiting
    log_info "Activating rate-limiting on /api/*..."
    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would set rate-limit: 100 req/min per IP on /api/*"
    else
        curl -s -X POST "$endpoint/api/admin/rate-limit" \
            -H "Content-Type: application/json" \
            -d '{"limit": 100, "window": "1m", "paths": ["/api/*"]}' \
            -o /dev/null 2>&1 && \
            log_ok "Rate-limiting activated" || \
            log_warn "Rate-limit endpoint not available (will use defaults)"
    fi

    # 4b. SCTGuard public mode
    log_info "Activating SCTGuard in public mode..."
    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would enable SCTGuard: Z-axis enforcement active"
    else
        curl -s -X POST "$endpoint/api/admin/sct-guard" \
            -H "Content-Type: application/json" \
            -d '{"mode": "public", "enforce_z_axis": true}' \
            -o /dev/null 2>&1 && \
            log_ok "SCTGuard public mode activated" || \
            log_warn "SCTGuard endpoint not available (will use defaults)"
    fi

    # 4c. BFTAggregator public mode
    log_info "Activating BFTAggregator in public mode..."
    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would enable BFTAggregator: Byzantine tolerance active"
    else
        curl -s -X POST "$endpoint/api/admin/bft" \
            -H "Content-Type: application/json" \
            -d '{"mode": "public", "outlier_sigma": 2.5, "max_byzantine_fraction": 0.33}' \
            -o /dev/null 2>&1 && \
            log_ok "BFTAggregator public mode activated" || \
            log_warn "BFT endpoint not available (will use defaults)"
    fi
}

activate_public_mode "http://localhost:3000"

# ─── Phase 5: Healthcheck Verification ──────────────────────────────────────

log_phase 5 "Healthcheck Verification"

HEALTHCHECK_OK=true
HEALTHCHECK_RESULTS=()

check_health_endpoint() {
    local name="$1"
    local url="$2"
    local expected_status="${3:-200}"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_dry "Would check: $name ($url)"
        return 0
    fi

    local http_code
    http_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$url" 2>/dev/null || echo "000")

    if [[ "$http_code" == "$expected_status" ]]; then
        log_ok "$name: HTTP $http_code"
        HEALTHCHECK_RESULTS+=("| $name | $url | 🟢 $http_code |")
    else
        HEALTHCHECK_OK=false
        FINDINGS+=("$name returned HTTP $http_code (expected $expected_status)")
        log_error "$name: HTTP $http_code (expected $expected_status)"
        HEALTHCHECK_RESULTS+=("| $name | $url | 🔴 $http_code |")
    fi
}

check_health_endpoint "/api/health" "http://localhost:3000/api/health" "200"
check_health_endpoint "/api/metrics" "http://localhost:3000/api/metrics" "200"
check_health_endpoint "/api/atlas/stats" "http://localhost:3000/api/atlas/stats" "200"

if [[ "$HEALTHCHECK_OK" == "false" ]]; then
    rollback "Healthcheck verification failed: ${#FINDINGS[@]} endpoint(s) unhealthy"
fi

# ─── Phase 6: Launch Report Generation ──────────────────────────────────────

log_phase 6 "Launch Report Generation"

# Collect metrics
PEER_COUNT="N/A"
CONSENSUS_LATENCY="N/A"
SLASHING_RATE="N/A"

if [[ "$DRY_RUN" == "false" ]]; then
    METRICS_RESPONSE=$(curl -s "http://localhost:3000/api/metrics" 2>/dev/null || echo "{}")
    PEER_COUNT=$(echo "$METRICS_RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('peers', 'N/A'))" 2>/dev/null || echo "N/A")
    CONSENSUS_LATENCY=$(echo "$METRICS_RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('consensus_latency_ms', 'N/A'))" 2>/dev/null || echo "N/A")
    SLASHING_RATE=$(echo "$METRICS_RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('slashing_rate', 'N/A'))" 2>/dev/null || echo "N/A")
fi

cat > "$PROJECT_ROOT/$REPORT_FILE" <<EOF
# Launch Day Report — SUCCESS ($REPORT_DATE)

## Status: 🟢 LAUNCH SUCCESS

### Launch Parameters
| Parameter | Value |
|-----------|-------|
| Profile | $PROFILE |
| Replicas | $REPLICAS |
| Dry Run | $DRY_RUN |
| Date | $REPORT_DATE |

### Initial Metrics
| Metric | Value |
|--------|-------|
| Active Peers | $PEER_COUNT |
| Consensus Latency | $CONSENSUS_LATENCY ms |
| Slashing Rate | $SLASHING_RATE |

### Healthcheck Results
| Endpoint | URL | Status |
|----------|-----|--------|
$(for result in "${HEALTHCHECK_RESULTS[@]}"; do echo "$result"; done)

### Findings
$(if [[ ${#FINDINGS[@]} -eq 0 ]]; then
    echo "- None (clean launch)"
else
    for finding in "${FINDINGS[@]}"; do echo "- $finding"; done
fi)

### Public Mode Status
- Rate-limiting: Active (100 req/min per IP)
- SCTGuard: Public mode (Z-axis enforcement)
- BFTAggregator: Public mode (Byzantine tolerance)

### Public URLs
- Dashboard: http://localhost:3000
- API: http://localhost:3000/api/health
- Metrics: http://localhost:3000/api/metrics
- Atlas: http://localhost:3000/api/atlas/stats

### Rollback Procedure
\`\`\`bash
docker compose --profile $PROFILE -f deploy/docker-compose.yml down
\`\`\`

---
*Generated by scripts/launch-day.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

log_ok "Launch report written to: $REPORT_FILE"

# ─── Success ────────────────────────────────────────────────────────────────

# Disable the EXIT trap since we succeeded
trap - EXIT INT TERM

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  🟢 LAUNCH SUCCESS — ed2kIA v2.1.0-sprint19 is LIVE${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Report: ${CYAN}$REPORT_FILE${NC}"
echo -e "  Dashboard: ${CYAN}http://localhost:3000${NC}"
echo -e "  API Health: ${CYAN}http://localhost:3000/api/health${NC}"
echo ""
echo "  Next steps:"
echo "    1. Monitor: tail -f logs/ed2kia.log"
echo "    2. Onboard community: ed2kia-onboard wizard"
echo "    3. Public dashboard: open web/public-dashboard.html"
echo ""

exit 0
