//! Alignment Loop v3 — Loop de alineación con verificación ZKP y mitigación de sesgos
//!
//! v3 introduces ZKP-verified steering signals, bias detection,
//! and confidence-based fallback to static mode when bias_score > 0.15.
//!
//! Feature-gated: `#[cfg(feature = "v1.2-sprint4")]`

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, VecDeque};
use thiserror::Error;
use tracing::{debug, info, warn};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors for Alignment Loop v3.
#[derive(Debug, Error)]
pub enum AlignmentV3Error {
    #[error("Invalid feedback: {0}")]
    InvalidFeedback(String),
    #[error("Steering verification failed")]
    SteeringVerificationFailed,
    #[error("Bias threshold exceeded: {score:.3} > {threshold:.3}")]
    BiasThresholdExceeded { score: f64, threshold: f64 },
    #[error("Confidence below minimum: {score:.3} < {min:.3}")]
    ConfidenceBelowMinimum { score: f64, min: f64 },
    #[error("No feedback data available")]
    NoFeedbackData,
    #[error("Model layer not found: {0}")]
    LayerNotFound(String),
    #[error("ZKP proof generation failed")]
    ZKPProofFailed,
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// Type of alignment feedback.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum FeedbackTypeV3 {
    /// Human preference feedback.
    HumanPreference,
    /// Automated metric feedback.
    AutomatedMetric,
    /// Cross-model consensus feedback.
    CrossModelConsensus,
    /// Ethical constraint feedback.
    EthicalConstraint,
}

impl std::fmt::Display for FeedbackTypeV3 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FeedbackTypeV3::HumanPreference => write!(f, "HUMAN_PREF"),
            FeedbackTypeV3::AutomatedMetric => write!(f, "AUTO_METRIC"),
            FeedbackTypeV3::CrossModelConsensus => write!(f, "CROSS_MODEL"),
            FeedbackTypeV3::EthicalConstraint => write!(f, "ETHICAL"),
        }
    }
}

/// Alignment feedback entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackEntryV3 {
    /// Source identifier.
    pub source_id: String,
    /// Feedback type.
    pub feedback_type: FeedbackTypeV3,
    /// Score (-1.0 to 1.0).
    pub score: f64,
    /// Confidence (0.0 to 1.0).
    pub confidence: f64,
    /// Model layer affected.
    pub layer_id: String,
    /// Timestamp (ms).
    pub timestamp_ms: u64,
    /// ZKP proof hash for verification.
    pub proof_hash: String,
}

impl FeedbackEntryV3 {
    /// Creates a new feedback entry with ZKP proof.
    pub fn new(
        source_id: String,
        feedback_type: FeedbackTypeV3,
        score: f64,
        confidence: f64,
        layer_id: String,
    ) -> Self {
        let proof_hash = compute_feedback_proof(&source_id, score, confidence);
        Self {
            source_id,
            feedback_type,
            score: score.clamp(-1.0, 1.0),
            confidence: confidence.clamp(0.0, 1.0),
            layer_id,
            timestamp_ms: current_timestamp_ms(),
            proof_hash,
        }
    }

    /// Verifies the ZKP proof hash.
    pub fn verify_proof(&self) -> bool {
        let expected = compute_feedback_proof(&self.source_id, self.score, self.confidence);
        self.proof_hash == expected
    }
}

/// Steering signal generated by the alignment loop.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SteeringSignalV3 {
    /// Signal identifier.
    pub signal_id: String,
    /// Target layer.
    pub layer_id: String,
    /// Adjustment vector (magnitude).
    pub adjustment: f64,
    /// Confidence score.
    pub confidence: f64,
    /// ZKP proof for verification.
    pub zkp_proof: String,
    /// Bias score (0.0 = no bias, 1.0 = high bias).
    pub bias_score: f64,
    /// Timestamp (ms).
    pub timestamp_ms: u64,
}

impl SteeringSignalV3 {
    /// Creates a new steering signal.
    pub fn new(
        signal_id: String,
        layer_id: String,
        adjustment: f64,
        confidence: f64,
        bias_score: f64,
    ) -> Self {
        let zkp_proof = compute_steering_proof(&signal_id, &layer_id, adjustment);
        Self {
            signal_id,
            layer_id,
            adjustment: adjustment.clamp(-1.0, 1.0),
            confidence: confidence.clamp(0.0, 1.0),
            zkp_proof,
            bias_score: bias_score.clamp(0.0, 1.0),
            timestamp_ms: current_timestamp_ms(),
        }
    }

    /// Verifies the ZKP proof.
    pub fn verify_zkp(&self) -> bool {
        let expected = compute_steering_proof(&self.signal_id, &self.layer_id, self.adjustment);
        self.zkp_proof == expected
    }

    /// Returns true if bias is acceptable.
    pub fn is_bias_acceptable(&self, threshold: f64) -> bool {
        self.bias_score <= threshold
    }
}

/// Result of an alignment cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlignmentResultV3 {
    /// Cycle number.
    pub cycle: u64,
    /// Generated steering signals.
    pub signals: Vec<SteeringSignalV3>,
    /// Overall alignment score.
    pub alignment_score: f64,
    /// Overall confidence.
    pub confidence: f64,
    /// Bias score.
    pub bias_score: f64,
    /// Fallback to static mode.
    pub fallback_to_static: bool,
    /// Timestamp (ms).
    pub timestamp_ms: u64,
}

/// Statistics for the alignment loop.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlignmentStatsV3 {
    /// Total cycles completed.
    pub total_cycles: u64,
    /// Total feedback processed.
    pub total_feedback: usize,
    /// Total signals generated.
    pub total_signals: usize,
    /// Average alignment score.
    pub avg_alignment_score: f64,
    /// Average confidence.
    pub avg_confidence: f64,
    /// Fallback count.
    pub fallback_count: usize,
    /// Bias detections.
    pub bias_detections: usize,
}

impl Default for AlignmentStatsV3 {
    fn default() -> Self {
        Self {
            total_cycles: 0,
            total_feedback: 0,
            total_signals: 0,
            avg_alignment_score: 0.5,
            avg_confidence: 0.5,
            fallback_count: 0,
            bias_detections: 0,
        }
    }
}

/// Configuration for Alignment Loop v3.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlignmentV3Config {
    /// Minimum confidence threshold.
    pub min_confidence: f64,
    /// Maximum acceptable bias score.
    pub max_bias_score: f64,
    /// Feedback window size.
    pub feedback_window: usize,
    /// Steering adjustment rate.
    pub adjustment_rate: f64,
    /// Number of layers to monitor.
    pub monitored_layers: Vec<String>,
}

impl Default for AlignmentV3Config {
    fn default() -> Self {
        Self {
            min_confidence: 0.88,
            max_bias_score: 0.15,
            feedback_window: 100,
            adjustment_rate: 0.1,
            monitored_layers: vec![
                "layer_0".to_string(),
                "layer_1".to_string(),
                "layer_2".to_string(),
            ],
        }
    }
}

// ---------------------------------------------------------------------------
// AlignmentLoopV3 Engine
// ---------------------------------------------------------------------------

/// Alignment loop v3 with ZKP verification and bias mitigation.
pub struct AlignmentLoopV3 {
    config: AlignmentV3Config,
    feedback_buffer: VecDeque<FeedbackEntryV3>,
    signals: Vec<SteeringSignalV3>,
    stats: AlignmentStatsV3,
    current_cycle: u64,
    /// Per-layer feedback aggregation
    layer_scores: BTreeMap<String, VecDeque<f64>>,
}

impl AlignmentLoopV3 {
    /// Creates a new alignment loop with default config.
    pub fn new() -> Self {
        Self::with_config(AlignmentV3Config::default())
    }

    /// Creates a loop with custom config.
    pub fn with_config(config: AlignmentV3Config) -> Self {
        Self {
            config,
            feedback_buffer: VecDeque::new(),
            signals: Vec::new(),
            stats: AlignmentStatsV3::default(),
            current_cycle: 0,
            layer_scores: BTreeMap::new(),
        }
    }

    /// Submits feedback to the alignment loop.
    pub fn submit_feedback(&mut self, feedback: FeedbackEntryV3) -> Result<(), AlignmentV3Error> {
        // Verify ZKP proof
        if !feedback.verify_proof() {
            return Err(AlignmentV3Error::SteeringVerificationFailed);
        }

        // Check confidence
        if feedback.confidence < self.config.min_confidence {
            return Err(AlignmentV3Error::ConfidenceBelowMinimum {
                score: feedback.confidence,
                min: self.config.min_confidence,
            });
        }

        self.feedback_buffer.push_back(feedback.clone());
        self.stats.total_feedback += 1;

        // Track per-layer scores
        self.layer_scores
            .entry(feedback.layer_id)
            .or_default()
            .push_back(feedback.score);

        // Enforce window size
        while self.feedback_buffer.len() > self.config.feedback_window {
            self.feedback_buffer.pop_front();
        }
        for scores in self.layer_scores.values_mut() {
            while scores.len() > self.config.feedback_window {
                scores.pop_front();
            }
        }

        info!(
            "AlignmentV3: submitted feedback from {} (score={:.3})",
            feedback.source_id, feedback.score
        );
        Ok(())
    }

    /// Runs an alignment cycle.
    pub fn run_cycle(&mut self) -> Result<AlignmentResultV3, AlignmentV3Error> {
        if self.feedback_buffer.is_empty() {
            return Err(AlignmentV3Error::NoFeedbackData);
        }

        self.current_cycle += 1;
        let mut cycle_signals = Vec::new();
        let mut total_alignment = 0.0;
        let mut total_confidence = 0.0;
        let mut layer_count = 0;
        let mut max_bias: f64 = 0.0;

        // Process each monitored layer
        for layer_id in &self.config.monitored_layers {
            let scores = self.layer_scores.get(layer_id);
            match scores {
                Some(scores) if !scores.is_empty() => {
                    let avg_score: f64 = scores.iter().sum::<f64>() / scores.len() as f64;
                    let confidence = self.compute_confidence(scores);
                    let bias_score = self.compute_bias_score(scores);

                    // Check bias threshold
                    if bias_score > self.config.max_bias_score {
                        self.stats.bias_detections += 1;
                        warn!(
                            "AlignmentV3: bias detected in {} (score={:.3})",
                            layer_id, bias_score
                        );
                    }
                    max_bias = max_bias.max(bias_score);

                    // Generate steering signal
                    let adjustment = self.config.adjustment_rate * avg_score;
                    let signal = SteeringSignalV3::new(
                        format!("sig-{}-{}", self.current_cycle, layer_id),
                        layer_id.clone(),
                        adjustment,
                        confidence,
                        bias_score,
                    );

                    cycle_signals.push(signal);
                    total_alignment += avg_score.abs();
                    total_confidence += confidence;
                    layer_count += 1;
                }
                _ => {
                    debug!("AlignmentV3: no feedback for layer {}", layer_id);
                }
            }
        }

        let avg_alignment = if layer_count > 0 {
            total_alignment / layer_count as f64
        } else {
            0.0
        };
        let avg_confidence = if layer_count > 0 {
            total_confidence / layer_count as f64
        } else {
            0.0
        };

        let fallback =
            max_bias > self.config.max_bias_score || avg_confidence < self.config.min_confidence;
        if fallback {
            self.stats.fallback_count += 1;
        }

        let result = AlignmentResultV3 {
            cycle: self.current_cycle,
            signals: cycle_signals,
            alignment_score: avg_alignment,
            confidence: avg_confidence,
            bias_score: max_bias,
            fallback_to_static: fallback,
            timestamp_ms: current_timestamp_ms(),
        };

        // Update stats
        self.stats.total_cycles += 1;
        self.stats.total_signals += result.signals.len();
        let alpha = 0.1;
        self.stats.avg_alignment_score =
            alpha * result.alignment_score + (1.0 - alpha) * self.stats.avg_alignment_score;
        self.stats.avg_confidence =
            alpha * result.confidence + (1.0 - alpha) * self.stats.avg_confidence;

        self.signals.extend(result.signals.clone());

        info!(
            "AlignmentV3: cycle {} complete (alignment={:.3}, bias={:.3}, fallback={})",
            result.cycle, result.alignment_score, result.bias_score, result.fallback_to_static
        );

        Ok(result)
    }

    /// Gets alignment statistics.
    pub fn get_stats(&self) -> AlignmentStatsV3 {
        self.stats.clone()
    }

    /// Gets recent signals.
    pub fn get_recent_signals(&self, limit: usize) -> Vec<&SteeringSignalV3> {
        self.signals.iter().rev().take(limit).collect()
    }

    /// Gets pending feedback count.
    pub fn pending_feedback_count(&self) -> usize {
        self.feedback_buffer.len()
    }

    /// Clears all feedback.
    pub fn clear_feedback(&mut self) {
        self.feedback_buffer.clear();
        self.layer_scores.clear();
    }

    /// Computes confidence from score distribution.
    fn compute_confidence(&self, scores: &VecDeque<f64>) -> f64 {
        if scores.len() < 2 {
            return 0.5;
        }
        let mean: f64 = scores.iter().sum::<f64>() / scores.len() as f64;
        let variance: f64 =
            scores.iter().map(|s| (s - mean).powi(2)).sum::<f64>() / scores.len() as f64;
        let std_dev = variance.sqrt();

        // Lower variance = higher confidence
        (1.0 / (1.0 + std_dev)).min(1.0)
    }

    /// Computes bias score from score distribution.
    fn compute_bias_score(&self, scores: &VecDeque<f64>) -> f64 {
        if scores.is_empty() {
            return 0.0;
        }
        let mean: f64 = scores.iter().sum::<f64>() / scores.len() as f64;

        // Check for skew (bias indicator)
        let skew: f64 = if scores.len() >= 3 {
            let variance: f64 =
                scores.iter().map(|s| (s - mean).powi(2)).sum::<f64>() / scores.len() as f64;
            let std_dev = variance.sqrt().max(1e-10);
            let cubed: f64 =
                scores.iter().map(|s| (s - mean).powi(3)).sum::<f64>() / scores.len() as f64;
            (cubed / std_dev.powi(3)).abs()
        } else {
            0.0
        };

        // Check for concentration (all scores same direction)
        let positive = scores.iter().filter(|&&s| s > 0.0).count() as f64;
        let concentration = (positive / scores.len() as f64 - 0.5).abs() * 2.0;

        (skew * 0.6 + concentration * 0.4).min(1.0)
    }
}

impl Default for AlignmentLoopV3 {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/// Computes ZKP proof hash for feedback.
pub fn compute_feedback_proof(source_id: &str, score: f64, confidence: f64) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"zkp-feedback-v3:");
    hasher.update(source_id.as_bytes());
    hasher.update(score.to_le_bytes());
    hasher.update(confidence.to_le_bytes());
    let result = hasher.finalize();
    format!("0x{}", hex::encode(result))
}

/// Computes ZKP proof hash for steering signal.
pub fn compute_steering_proof(signal_id: &str, layer_id: &str, adjustment: f64) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"zkp-steering-v3:");
    hasher.update(signal_id.as_bytes());
    hasher.update(layer_id.as_bytes());
    hasher.update(adjustment.to_le_bytes());
    let result = hasher.finalize();
    format!("0x{}", hex::encode(result))
}

/// Returns current timestamp in milliseconds.
fn current_timestamp_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_feedback(source: &str, score: f64, layer: &str) -> FeedbackEntryV3 {
        FeedbackEntryV3::new(
            source.to_string(),
            FeedbackTypeV3::HumanPreference,
            score,
            0.95,
            layer.to_string(),
        )
    }

    #[test]
    fn test_loop_creation() {
        let loop_v3 = AlignmentLoopV3::new();
        assert_eq!(loop_v3.get_stats().total_cycles, 0);
    }

    #[test]
    fn test_submit_feedback() {
        let mut loop_v3 = AlignmentLoopV3::new();
        let feedback = make_feedback("user-1", 0.8, "layer_0");
        loop_v3.submit_feedback(feedback).unwrap();
        assert_eq!(loop_v3.pending_feedback_count(), 1);
    }

    #[test]
    fn test_submit_low_confidence() {
        let mut loop_v3 = AlignmentLoopV3::new();
        let mut feedback = make_feedback("user-1", 0.8, "layer_0");
        feedback.confidence = 0.5;
        feedback.proof_hash = compute_feedback_proof("user-1", 0.8, 0.5);
        let result = loop_v3.submit_feedback(feedback);
        assert!(result.is_err());
    }

    #[test]
    fn test_submit_tampered_proof() {
        let mut loop_v3 = AlignmentLoopV3::new();
        let mut feedback = make_feedback("user-1", 0.8, "layer_0");
        feedback.proof_hash = "0xtampered".to_string();
        let result = loop_v3.submit_feedback(feedback);
        assert!(result.is_err());
    }

    #[test]
    fn test_run_cycle() {
        let config = AlignmentV3Config {
            max_bias_score: 0.5, // Allow higher bias since all scores are positive
            min_confidence: 0.8, // Allow lower confidence for spread scores
            ..Default::default()
        };
        let mut loop_v3 = AlignmentLoopV3::with_config(config);
        for i in 0..10 {
            let score = 0.5 + (i as f64 * 0.05);
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), score, "layer_0"))
                .unwrap();
        }

        let result = loop_v3.run_cycle().unwrap();
        assert!(result.signals.len() >= 1);
        assert!(!result.fallback_to_static);
        assert!(result.alignment_score > 0.0);
    }

    #[test]
    fn test_run_cycle_no_feedback() {
        let mut loop_v3 = AlignmentLoopV3::new();
        let result = loop_v3.run_cycle();
        assert!(result.is_err());
    }

    #[test]
    fn test_bias_detection() {
        let mut loop_v3 = AlignmentLoopV3::new();
        // Submit highly skewed feedback
        for i in 0..20 {
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), 1.0, "layer_0"))
                .unwrap();
        }

        let result = loop_v3.run_cycle().unwrap();
        assert!(result.bias_score > 0.0);
    }

    #[test]
    fn test_fallback_to_static() {
        let config = AlignmentV3Config {
            max_bias_score: 0.01, // Very strict
            ..Default::default()
        };
        let mut loop_v3 = AlignmentLoopV3::with_config(config);
        for i in 0..20 {
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), 1.0, "layer_0"))
                .unwrap();
        }

        let result = loop_v3.run_cycle().unwrap();
        assert!(result.fallback_to_static);
    }

    #[test]
    fn test_steering_signal_verification() {
        let signal = SteeringSignalV3::new("s1".to_string(), "layer_0".to_string(), 0.5, 0.9, 0.1);
        assert!(signal.verify_zkp());
        assert!(signal.is_bias_acceptable(0.15));
    }

    #[test]
    fn test_steering_signal_bias_rejection() {
        let signal = SteeringSignalV3::new("s1".to_string(), "layer_0".to_string(), 0.5, 0.9, 0.2);
        assert!(!signal.is_bias_acceptable(0.15));
    }

    #[test]
    fn test_feedback_proof_verification() {
        let feedback = make_feedback("u1", 0.8, "layer_0");
        assert!(feedback.verify_proof());
    }

    #[test]
    fn test_stats_tracking() {
        let mut loop_v3 = AlignmentLoopV3::new();
        for i in 0..5 {
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), 0.7, "layer_0"))
                .unwrap();
        }
        loop_v3.run_cycle().unwrap();

        let stats = loop_v3.get_stats();
        assert_eq!(stats.total_cycles, 1);
        assert_eq!(stats.total_feedback, 5);
    }

    #[test]
    fn test_clear_feedback() {
        let mut loop_v3 = AlignmentLoopV3::new();
        loop_v3
            .submit_feedback(make_feedback("u1", 0.8, "layer_0"))
            .unwrap();
        loop_v3.clear_feedback();
        assert_eq!(loop_v3.pending_feedback_count(), 0);
    }

    #[test]
    fn test_feedback_window_limit() {
        let config = AlignmentV3Config {
            feedback_window: 5,
            ..Default::default()
        };
        let mut loop_v3 = AlignmentLoopV3::with_config(config);
        for i in 0..10 {
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), 0.5, "layer_0"))
                .unwrap();
        }
        assert_eq!(loop_v3.pending_feedback_count(), 5);
    }

    #[test]
    fn test_get_recent_signals() {
        let mut loop_v3 = AlignmentLoopV3::new();
        for i in 0..5 {
            loop_v3
                .submit_feedback(make_feedback(&format!("u{}", i), 0.7, "layer_0"))
                .unwrap();
        }
        loop_v3.run_cycle().unwrap();

        let signals = loop_v3.get_recent_signals(3);
        assert!(!signals.is_empty());
    }

    #[test]
    fn test_multiple_cycles() {
        let mut loop_v3 = AlignmentLoopV3::new();
        for cycle in 0..3 {
            for i in 0..5 {
                let score = 0.5 + (cycle as f64 * 0.1);
                loop_v3
                    .submit_feedback(make_feedback(&format!("u{}", i), score, "layer_0"))
                    .unwrap();
            }
            loop_v3.run_cycle().unwrap();
        }

        assert_eq!(loop_v3.get_stats().total_cycles, 3);
    }

    #[test]
    fn test_config_default() {
        let config = AlignmentV3Config::default();
        assert_eq!(config.min_confidence, 0.88);
        assert_eq!(config.max_bias_score, 0.15);
    }

    #[test]
    fn test_loop_default() {
        let loop_v3 = AlignmentLoopV3::default();
        assert_eq!(loop_v3.get_stats().total_cycles, 0);
    }

    #[test]
    fn test_feedback_type_display() {
        let ft = FeedbackTypeV3::HumanPreference;
        assert_eq!(format!("{}", ft), "HUMAN_PREF");
    }

    #[test]
    fn test_proof_consistency() {
        let h1 = compute_feedback_proof("u1", 0.8, 0.95);
        let h2 = compute_feedback_proof("u1", 0.8, 0.95);
        assert_eq!(h1, h2);
    }

    #[test]
    fn test_proof_uniqueness() {
        let h1 = compute_feedback_proof("u1", 0.8, 0.95);
        let h2 = compute_feedback_proof("u2", 0.8, 0.95);
        assert_ne!(h1, h2);
    }

    #[test]
    fn test_steering_proof_consistency() {
        let h1 = compute_steering_proof("s1", "l0", 0.5);
        let h2 = compute_steering_proof("s1", "l0", 0.5);
        assert_eq!(h1, h2);
    }

    #[test]
    fn test_score_clamping() {
        let mut loop_v3 = AlignmentLoopV3::new();
        let feedback = FeedbackEntryV3::new(
            "u1".to_string(),
            FeedbackTypeV3::HumanPreference,
            2.0,
            0.95,
            "layer_0".to_string(),
        );
        assert_eq!(feedback.score, 1.0); // Clamped
    }

    #[test]
    fn test_error_display() {
        let err = AlignmentV3Error::BiasThresholdExceeded {
            score: 0.2,
            threshold: 0.15,
        };
        let msg = format!("{}", err);
        assert!(msg.contains("0.2"));
    }
}
